stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bentastic27/registry-arm:${CICD_EXECUTION_SEQUENCE}
timeout: 60
notification: {}
